### ISSUE TITLE
1.3.5 broke the functionality?

### ISSUE THREAD

**Issue by Stakker** [scambier/obsidian-no-dupe-leaves#13] opened 2023-06-02 07:47 UTC
Doesn't seem to be working anymore :-/

I know it's a hack so things like this are expected, but would be nice to get it working anyway if you get the chance to fix it :-)

(I have added my comment to the proper Obsidian feature request thread too…)

**Comment by scambier** [comment] 2023-06-02 08:49
Duplicate of #12

**Closed as completed by scambier** 2023-06-02 08:49 UTC

**Comment by scambier** [comment] 2023-06-02 08:53
Though yes, I suspect Obsidian changed something in the way links are handled. They introduced and then reverted some changes a week ago, so the internal plumbing probably changed.

**Comment by Stakker** [comment] 2023-06-02 15:01
Yeah all right.

**Comment by scambier** [comment] 2023-06-03 16:06
Should be fixed with 0.0.10

**Comment by Stakker** [comment] 2023-06-05 07:46
Yeah, works again (*phew*). Thanks for the fix, I appeciate it! 👍

I sure hope the Obsidian devs are working on changing this behavior properly… At least the thread for this is marked as "Valuable", so it's not impossible…
