### ISSUE TITLE
Is it me, or does it straight up not work?

### ISSUE THREAD

**Issue by Z3DT** [scambier/obsidian-no-dupe-leaves#12] opened 2023-05-27 14:47 UTC
With this plugin enabled, if I have something open in a tab already and then click a link to that file in another tab, I still get a duplicate tab.  This happens both with tabs and with two side by side pages like in de gif in the plugin description.

Recording of it not working:
https://www.youtube.com/watch?v=Tk0nbbTBO_0

**Comment by scambier** [comment] 2023-05-27 15:19
I have just updated the plugin with a few corrections. Maybe that will fix your issue.

**Comment by Z3DT** [comment] 2023-05-27 15:59
I have updated the plugin, but no change in behavior.

**Comment by czottmann** [comment] 2023-06-01 13:57
Same here. Obsidian 1.3.4 on macOS.

**Comment by scambier** [comment] 2023-06-02 06:31
It works on one of my vaults, but not the other 🤔 At least it's reproducible

**Comment by czottmann** [comment] 2023-06-02 08:33
> It works on one of my vaults, but not the other 

The joys of software development, amirite 😂

**Comment by scambier** [comment] 2023-06-03 16:02
Should be fixed (at least it passed my tests), you can reopen if that's not the case :)

**Comment by czottmann** [comment] 2023-06-03 18:10
No dice, I'm afraid, 0.0.10 doesn't change anything for me. I've restarted Obs, then checked dev tools for errors (none).

**Comment by scambier** [comment] 2023-06-04 05:12
Ok, can you give me reproduction steps I can apply on an empty vault please? Thank you!

**Comment by czottmann** [comment] 2023-06-04 08:36
I just realized I am probably wrong to expect your plugin to work when using the hotkeys of PeriodicNotes etc. because the hotkeys likely use core functionality which you mentioned in the README. Correct?

If so, you can close the ticket again on my behalf, and I apologize for wasting your time.

**Comment by scambier** [comment] 2023-06-04 09:21
👍 No problem. Yeah, the plugin only overwrites the `openLinkText()` function, which is called when clicking on links in notes. AFAIK it does not work with core plugins, and may or may not work with community plugins, depending on how they're built,

**Closed as completed by scambier** 2023-06-04 09:21 UTC
Labels: bug
